apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component
  namespace: skabashn
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-
      labels:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: skabashn
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio/e2e-tests
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:skabashn-component-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ab259a6fef091698b0fc145537338fa78f521c1f
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component/$(tt.params.git-revision)
    status: {}
status: {}
